"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, GitMerge, LoaderCircle, Mail, Phone, Save, ShieldCheck, UploadCloud, UserPlus, Users } from "lucide-react";
import { PageHeader } from "@/components/ui";
import { APPLICATION_STAGES } from "@/lib/recruiting";
import type { CandidateProfile } from "@/lib/types";

type Position={id:string;title:string;status:string};
type ExistingCandidate={id:string;displayName:string;currentRole:string|null;applications:Array<{job:{id:string}}>};
type DuplicateCandidate={id:string;displayName:string;currentRole:string|null;maskedEmail:string|null;maskedPhone:string|null;matchingFields:Array<"email"|"phone">};
type FormState={displayName:string;email:string;phone:string;currentRole:string;yearsOfExperience:string;education:string;skills:string;source:string;jobId:string;stage:string};
const emptyForm:FormState={displayName:"",email:"",phone:"",currentRole:"",yearsOfExperience:"",education:"",skills:"",source:"",jobId:"",stage:"RECEIVED"};

export default function NewCandidatePage(){
  const router=useRouter();const [form,setForm]=useState<FormState>(emptyForm);const [positions,setPositions]=useState<Position[]>([]);const [existing,setExisting]=useState<ExistingCandidate[]>([]);const [mode,setMode]=useState<"new"|"existing">("new");const [existingId,setExistingId]=useState("");const [file,setFile]=useState<File|null>(null);const [parsing,setParsing]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [duplicates,setDuplicates]=useState<DuplicateCandidate[]>([]);
  useEffect(()=>{void (async()=>{try{const [jobsResponse,candidatesResponse]=await Promise.all([fetch("/api/jobs"),fetch("/api/candidates")]);const jobs=await jobsResponse.json();const candidates=await candidatesResponse.json();if(!jobsResponse.ok)throw new Error(jobs.error||"职位读取失败");if(!candidatesResponse.ok)throw new Error(candidates.error||"人才库读取失败");setPositions(jobs.jobs||[]);setExisting(candidates.candidates||[]);const requested=new URLSearchParams(window.location.search).get("positionId");if(requested)setForm(current=>({...current,jobId:requested}))}catch(e){setError(e instanceof Error?e.message:"基础数据读取失败")}})()},[]);
  const availableExisting=useMemo(()=>existing.filter(candidate=>!form.jobId||!candidate.applications.some(application=>application.job.id===form.jobId)),[existing,form.jobId]);
  function update(key:keyof FormState,value:string){setDuplicates([]);setForm(current=>({...current,[key]:value}))}
  async function chooseFile(event:ChangeEvent<HTMLInputElement>){const selected=event.target.files?.[0];if(!selected)return;setFile(selected);setParsing(true);setError("");try{const body=new FormData();body.append("file",selected);body.append("anonymize","false");const response=await fetch("/api/resume/parse",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.error||"简历解析失败");const candidate=data.result as CandidateProfile;setForm(current=>({...current,displayName:candidate.displayName==="姓名待确认"?current.displayName:candidate.displayName,currentRole:candidate.currentRole||current.currentRole,yearsOfExperience:String(candidate.yearsOfExperience||""),education:candidate.education||current.education,skills:candidate.skills.join("、"),email:data.contact?.email||current.email,phone:data.contact?.phone||current.phone}))}catch(e){setError(e instanceof Error?e.message:"简历解析失败，可继续手动填写")}finally{setParsing(false)}}
  async function submit(mergeCandidateId?:string){setError("");if(mode==="existing"){if(!form.jobId||!existingId){setError("请选择招聘职位和人才库候选人");return}setSaving(true);try{const response=await fetch("/api/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({candidateId:existingId,jobId:form.jobId,stage:form.stage})});const data=await response.json();if(!response.ok)throw new Error(data.error||"加入招聘流程失败");router.push(`/candidates/${existingId}`)}catch(e){setError(e instanceof Error?e.message:"加入招聘流程失败")}finally{setSaving(false)}return}
    if(!form.displayName.trim()){setError("请填写候选人姓名");return}setSaving(true);try{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,value));if(file)body.append("file",file);if(mergeCandidateId)body.append("mergeCandidateId",mergeCandidateId);const response=await fetch("/api/candidates",{method:"POST",body});const data=await response.json();if(response.status===409&&data.code==="DUPLICATE_CANDIDATE"){setDuplicates(data.duplicates||[]);return}if(!response.ok)throw new Error(data.error||"候选人保存失败");router.push(`/candidates/${data.candidateId}`)}catch(e){setError(e instanceof Error?e.message:"候选人保存失败")}finally{setSaving(false)}}
  return <div className="fade-up"><div className="mb-4"><Link href="/candidates" className="inline-flex items-center gap-2 text-xs font-semibold text-[#67746d]"><ArrowLeft size={14}/>返回候选人管理</Link></div><PageHeader eyebrow="Talent Pool" title="添加候选人" description="新建人才库档案，或将已有候选人加入指定职位的招聘流程。"/>
    {form.jobId&&<div className="mb-5 flex rounded-xl bg-[#eef2ef] p-1"><button onClick={()=>setMode("new")} className={`flex-1 rounded-lg px-4 py-2.5 text-xs font-semibold ${mode==="new"?"bg-white text-brand-700 shadow-sm":"text-[#6f7b74]"}`}><UserPlus size={14} className="mr-2 inline"/>新建候选人</button><button onClick={()=>setMode("existing")} className={`flex-1 rounded-lg px-4 py-2.5 text-xs font-semibold ${mode==="existing"?"bg-white text-brand-700 shadow-sm":"text-[#6f7b74]"}`}><Users size={14} className="mr-2 inline"/>从人才库选择</button></div>}
    {mode==="existing"?<section className="panel mx-auto max-w-2xl p-5"><h2 className="font-semibold">加入职位流程</h2><p className="mt-1 text-xs text-[#7c8881]">不会重复创建候选人档案，只新增一条职位招聘流程。</p><div className="mt-5 grid gap-4"><label><span className="label">招聘职位</span><select className="input" value={form.jobId} onChange={event=>update("jobId",event.target.value)}><option value="">请选择职位</option>{positions.map(position=><option key={position.id} value={position.id}>{position.title}</option>)}</select></label><label><span className="label">人才库候选人</span><select className="input" value={existingId} onChange={event=>setExistingId(event.target.value)}><option value="">请选择候选人</option>{availableExisting.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.displayName} · {candidate.currentRole||"当前职位待补充"}</option>)}</select></label><label><span className="label">初始招聘阶段</span><select className="input" value={form.stage} onChange={event=>update("stage",event.target.value)}>{APPLICATION_STAGES.map(stage=><option key={stage.value} value={stage.value}>{stage.label}</option>)}</select></label></div>{error&&<ErrorBox text={error}/>}<button disabled={saving} onClick={()=>void submit()} className="btn-primary mt-5 w-full"><Save size={15}/>{saving?"加入中…":"加入招聘流程"}</button></section>:
    <div className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><section className="panel p-5"><h2 className="font-semibold">原始简历</h2><p className="mt-1 text-xs leading-5 text-[#7c8881]">上传后自动提取基础信息；保存后可从候选人详情受控下载。</p><label className="mt-5 grid min-h-52 cursor-pointer place-items-center rounded-2xl border border-dashed border-[#cbd6d0] bg-[#fafcfb] p-5 text-center hover:border-brand-500 hover:bg-brand-50"><input type="file" accept=".pdf,.docx,.txt" className="hidden" onChange={chooseFile}/>{parsing?<LoaderCircle className="animate-spin text-brand-600" size={28}/>:<UploadCloud className="text-brand-600" size={28}/>}<div><p className="mt-3 text-sm font-semibold">{file?.name||"选择 PDF、DOCX 或 TXT 简历"}</p><p className="mt-1 text-xs text-[#89948e]">最大 5MB</p></div></label><div className="mt-4 flex gap-2 rounded-xl bg-[#f3faf6] p-3 text-[11px] leading-5 text-[#5f7067]"><ShieldCheck size={15} className="mt-0.5 shrink-0 text-brand-600"/>模型分析前会脱敏电话、邮箱和身份证号；联系方式只在详情页按需显示。</div></section>
      <section className="panel p-5"><h2 className="font-semibold">候选人信息</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="姓名 *" value={form.displayName} onChange={value=>update("displayName",value)}/><Field label="当前职位" value={form.currentRole} onChange={value=>update("currentRole",value)}/><Field label="电话" value={form.phone} onChange={value=>update("phone",value)}/><Field label="邮箱" type="email" value={form.email} onChange={value=>update("email",value)}/><Field label="工作年限" type="number" value={form.yearsOfExperience} onChange={value=>update("yearsOfExperience",value)}/><Field label="教育背景" value={form.education} onChange={value=>update("education",value)}/><div className="md:col-span-2"><Field label="技能标签（用逗号或顿号分隔）" value={form.skills} onChange={value=>update("skills",value)}/></div><Field label="候选人来源" value={form.source} onChange={value=>update("source",value)} placeholder="例如：官网、内推、招聘网站"/><label><span className="label">招聘职位</span><select className="input" value={form.jobId} onChange={event=>update("jobId",event.target.value)}><option value="">暂不关联，加入人才库</option>{positions.map(position=><option key={position.id} value={position.id}>{position.title}{position.status==="CLOSED"?"（已关闭）":""}</option>)}</select></label>{form.jobId&&<label><span className="label">当前招聘阶段</span><select className="input" value={form.stage} onChange={event=>update("stage",event.target.value)}>{APPLICATION_STAGES.map(stage=><option key={stage.value} value={stage.value}>{stage.label}</option>)}</select></label>}</div>{error&&<ErrorBox text={error}/>}<DuplicatePanel items={duplicates} saving={saving} onMerge={id=>void submit(id)}/><button disabled={saving||parsing} onClick={()=>void submit()} className="btn-primary mt-5 w-full"><Save size={15}/>{saving?"保存中…":"保存候选人"}</button></section></div>}
  </div>
}

function Field({label,value,onChange,type="text",placeholder}:{label:string;value:string;onChange:(value:string)=>void;type?:string;placeholder?:string}){return <label><span className="label">{label}</span><input className="input" type={type} min={type==="number"?0:undefined} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder}/></label>}
function ErrorBox({text}:{text:string}){return <div className="mt-4 rounded-xl bg-[#fff3f1] px-4 py-3 text-xs text-[#a84d43]">{text}</div>}
function DuplicatePanel({items,saving,onMerge}:{items:DuplicateCandidate[];saving:boolean;onMerge:(id:string)=>void}){if(!items.length)return null;return <div className="mt-4 rounded-xl border border-[#ecd9b9] bg-[#fff9ed] p-4"><div className="flex gap-2"><GitMerge size={17} className="mt-0.5 shrink-0 text-[#a9792f]"/><div><p className="text-xs font-semibold text-[#725a31]">发现可能重复的候选人档案</p><p className="mt-1 text-[11px] leading-5 text-[#806f50]">手机号或邮箱任一相同即视为重复。请选择合并，系统不会创建第二份档案。</p></div></div><div className="mt-3 space-y-2">{items.map(item=><div key={item.id} className="rounded-lg border border-[#eadfc9] bg-white p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold">{item.displayName} · {item.currentRole||"当前职位待补充"}</p><div className="mt-1 flex flex-wrap gap-3 text-[10px] text-[#7a6d55]">{item.maskedPhone&&<span className="flex items-center gap-1"><Phone size={11}/>{item.maskedPhone}</span>}{item.maskedEmail&&<span className="flex items-center gap-1"><Mail size={11}/>{item.maskedEmail}</span>}</div><p className="mt-1 text-[10px] font-semibold text-[#9a6a23]">命中：{item.matchingFields.map(field=>field==="phone"?"手机号":"邮箱").join("、")}</p></div><div className="flex gap-2"><Link href={`/candidates/${item.id}`} target="_blank" className="btn-secondary !px-3 !py-2">查看档案</Link><button disabled={saving} onClick={()=>onMerge(item.id)} className="btn-primary !px-3 !py-2"><GitMerge size={13}/>合并保存</button></div></div></div>)}</div></div>}
