"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CalendarClock, FileSearch, Lightbulb, MessageSquareText, Sparkles, Users } from "lucide-react";
import { AiNotice, EmptyState, LoadingState, PageHeader } from "@/components/ui";
import { FUNNEL_STAGES } from "@/lib/funnel-analysis";
import type { FunnelAnalysis, FunnelData } from "@/lib/types";

type Overview={stats:{activePositions:number;candidates:number;receivedResumes:number;pendingInterviews:number;aiAnalyses:number};positions:Array<{id:string;title:string;department:string|null;candidateCount:number;stage:string;progress:number}>;funnel:FunnelData;averageMatch:number|null;insight:FunnelAnalysis|null};

export default function HomePage(){
  const [data,setData]=useState<Overview|null>(null);const [error,setError]=useState("");
  useEffect(()=>{void (async()=>{try{const response=await fetch("/api/overview");const result=await response.json();if(!response.ok)throw new Error(result.error||"概览读取失败");setData(result)}catch(e){setError(e instanceof Error?e.message:"概览读取失败")}})()},[]);
  const stats=data?[{label:"进行中职位",value:data.stats.activePositions,tip:"当前开放招聘",icon:BriefcaseBusiness,color:"bg-[#edf7f2] text-brand-600"},{label:"收到简历",value:data.stats.receivedResumes,tip:"实际招聘流程人次",icon:FileSearch,color:"bg-[#f0f4fb] text-[#5677ad]"},{label:"人才库人数",value:data.stats.candidates,tip:"候选人去重统计",icon:Users,color:"bg-[#eef3fb] text-[#4b73b7]"},{label:"待进行面试",value:data.stats.pendingInterviews,tip:"已排期且尚未开始",icon:CalendarClock,color:"bg-[#faf3e8] text-[#b77a28]"},{label:"AI 匹配分析",value:data.stats.aiAnalyses,tip:"已保存分析报告",icon:Sparkles,color:"bg-[#f4effb] text-[#7652ae]"}]:[];
  return <div className="fade-up"><PageHeader eyebrow="Overview" title="招聘概览" description="所有人数、职位进展和招聘漏斗均来自当前人才库与招聘流程。" action={<Link href="/candidates/new" className="btn-primary"><Users size={16}/>添加候选人</Link>}/>
    {error?<div className="panel p-6 text-sm text-[#a84d43]">{error}</div>:!data?<div className="panel p-5"><LoadingState label="正在汇总招聘数据…"/></div>:<>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{stats.map(({label,value,tip,icon:Icon,color})=><div className="panel p-5" key={label}><div className={`grid size-10 place-items-center rounded-xl ${color}`}><Icon size={19}/></div><p className="mt-5 text-3xl font-bold tracking-[-.04em]">{value}</p><p className="mt-1 text-sm text-[#65726c]">{label}</p><p className="mt-1 text-[11px] text-[#89938e]">{tip}</p></div>)}</div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf0ee] px-5 py-4"><div><h2 className="font-semibold">进行中的职位</h2><p className="mt-0.5 text-xs text-[#7b8781]">候选人数与阶段来自实际招聘流程</p></div><Link href="/jobs" className="text-xs font-semibold text-brand-600">查看全部</Link></div>{data.positions.length?<div className="divide-y divide-[#eef1ef]">{data.positions.slice(0,5).map(position=><div key={position.id} className="grid items-center gap-3 px-5 py-4 sm:grid-cols-[1.4fr_.8fr_1fr]"><div><p className="text-sm font-semibold">{position.title}</p><p className="mt-1 text-xs text-[#84908a]">{position.department||"部门待补充"} · {position.candidateCount} 位候选人</p></div><span className="w-fit rounded-full bg-brand-50 px-2.5 py-1 text-[11px] font-semibold text-brand-700">{position.stage}</span><div className="flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-[#edf0ee]"><div className="h-1.5 rounded-full bg-brand-500" style={{width:`${position.progress}%`}}/></div><span className="w-8 text-right text-xs font-semibold">{position.progress}%</span></div></div>)}</div>:<div className="p-5"><EmptyState title="暂无招聘职位" description="完成JD分析并保存职位后，实际进展会显示在这里"/></div>}</section>
        <section className="panel p-5"><div className="flex items-center gap-2"><div className="grid size-8 place-items-center rounded-lg bg-brand-50 text-brand-600"><Lightbulb size={17}/></div><div><h2 className="text-sm font-semibold">招聘数据提示</h2><p className="text-[11px] text-[#8a958f]">基于当前实际流程</p></div></div>{data.insight?<div className="my-5 rounded-xl bg-[#f7faf8] p-4"><p className="text-xs font-semibold text-[#56635c]">优先关注：{data.insight.bottleneck}</p><p className="mt-2 text-xs leading-5 text-[#6e7a74]">{data.insight.summary}</p><p className="mt-2 text-xs font-medium text-brand-700">{data.insight.recommendations[0]}</p></div>:<div className="my-5 rounded-xl bg-[#f7faf8] p-4 text-xs leading-5 text-[#6e7a74]">添加候选人并关联招聘职位后，系统会基于实际转化生成提示。</div>}<div className="flex items-center justify-between text-xs"><span className="text-[#69766f]">人职匹配均分</span><span className="font-bold">{data.averageMatch===null?"—":`${data.averageMatch}%`}</span></div><Link href="/dashboard" className="mt-5 flex items-center gap-2 text-xs font-semibold text-brand-600">查看完整漏斗 <ArrowRight size={14}/></Link></section></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="panel p-5"><div className="mb-5"><h2 className="font-semibold">招聘漏斗</h2><p className="mt-0.5 text-xs text-[#7b8781]">全部招聘职位实时汇总</p></div><div className="flex h-44 items-end justify-between gap-3">{FUNNEL_STAGES.map((stage,index)=>{const value=data.funnel[stage.key];const height=data.funnel.received?Math.max(value?10:2,Math.round(value/data.funnel.received*100)):2;return <div key={stage.key} className="flex h-full flex-1 flex-col justify-end"><p className="mb-2 text-center text-sm font-bold">{value}</p><div className={`mx-auto w-full max-w-16 rounded-t-lg ${index===0?"bg-[#b9ddcd]":"bg-brand-500"}`} style={{height:`${height}%`}}/><p className="mt-2 text-center text-[11px] text-[#7d8882]">{stage.short}</p></div>})}</div></section><section className="panel p-5"><h2 className="font-semibold">快捷开始</h2><div className="mt-4 grid gap-2.5">{[{href:"/jd-analysis",icon:BriefcaseBusiness,title:"分析职位 JD",sub:"生成职位能力画像"},{href:"/candidates/new",icon:FileSearch,title:"添加候选人",sub:"建立人才库并关联招聘职位"},{href:"/interview",icon:MessageSquareText,title:"准备结构化面试",sub:"生成 STAR 问题"}].map(({href,icon:Icon,title,sub})=><Link href={href} key={href} className="group flex items-center gap-3 rounded-xl border border-[#e5eae7] p-3 hover:border-brand-100 hover:bg-brand-50"><div className="grid size-9 place-items-center rounded-lg bg-[#f2f5f3] text-[#59675f]"><Icon size={17}/></div><div className="flex-1"><p className="text-xs font-semibold">{title}</p><p className="mt-0.5 text-[11px] text-[#8a958f]">{sub}</p></div><ArrowRight size={14} className="text-[#a2aca7]"/></Link>)}</div></section></div><div className="mt-6"><AiNotice compact/></div>
    </>}
  </div>
}
