"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertCircle, Briefcase, ChevronRight, Filter, Plus, RefreshCw, Search, UserRound } from "lucide-react";
import { EmptyState, LoadingState, PageHeader } from "@/components/ui";
import { MATCH_INTERVIEW_THRESHOLD } from "@/lib/match-assessment";
import { stageLabel } from "@/lib/recruiting";

type Position={id:string;title:string;status:string};
type Candidate={id:string;displayName:string;currentRole:string|null;yearsOfExperience:number|null;skills:string[];updatedAt:string;hasResume:boolean;applications:Array<{id:string;stage:string;job:Position}>;latestMatch:null|{overallScore:number;hrDecision:string|null;strengths:string[];risks:string[]}};
const decisions:Record<string,string>={PENDING:"待处理",INTERVIEW:"进入面试",HOLD:"保留",RECOMMEND:"推荐",REJECT:"不推荐"};

export default function CandidatesPage(){
  const [items,setItems]=useState<Candidate[]>([]);const [positions,setPositions]=useState<Position[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState("");const [decisionFilter,setDecisionFilter]=useState("ALL");const [positionFilter,setPositionFilter]=useState("ALL");const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/candidates");const data=await response.json();if(!response.ok)throw new Error(data.error||"候选人数据读取失败");setItems(data.candidates||[]);setPositions(data.positions||[])}catch(e){setError(e instanceof Error?e.message:"候选人数据读取失败")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>items.filter(item=>{const search=[item.displayName,item.currentRole,...item.applications.map(application=>application.job.title)].filter(Boolean).join(" ").toLowerCase().includes(query.toLowerCase());const decision=decisionFilter==="ALL"||(item.latestMatch?.hrDecision||"PENDING")===decisionFilter;const position=positionFilter==="ALL"||(positionFilter==="POOL"?item.applications.length===0:item.applications.some(application=>application.job.id===positionFilter));return search&&decision&&position}),[items,query,decisionFilter,positionFilter]);
  return <div className="fade-up"><PageHeader eyebrow="Talent Pipeline" title="候选人管理" description="统一维护企业人才库，并跟踪候选人在不同招聘职位中的实际进展。" action={<Link href="/candidates/new" className="btn-primary"><Plus size={15}/>添加候选人</Link>}/>
    <div className="mb-5 grid gap-4 sm:grid-cols-3">{[{l:"人才库总人数",v:items.length},{l:"进入招聘流程",v:items.filter(item=>item.applications.length>0).length},{l:"建议进入面试",v:items.filter(item=>(item.latestMatch?.overallScore||0)>=MATCH_INTERVIEW_THRESHOLD).length}].map(item=><div key={item.l} className="panel p-4"><p className="text-xs text-[#7b8781]">{item.l}</p><p className="mt-2 text-2xl font-bold">{item.v}</p></div>)}</div>
    <div className="panel overflow-hidden"><div className="grid gap-3 border-b border-[#e7ece9] p-4 lg:grid-cols-[1fr_210px_180px]"><div className="relative"><Search size={15} className="absolute left-3 top-3 text-[#8a958f]"/><input value={query} onChange={event=>setQuery(event.target.value)} className="input !pl-9" placeholder="搜索候选人、职位或当前职位"/></div><div className="flex items-center gap-2"><Briefcase size={14} className="shrink-0 text-[#7b8781]"/><select value={positionFilter} onChange={event=>setPositionFilter(event.target.value)} className="input"><option value="ALL">全部招聘职位</option><option value="POOL">仅人才库未关联</option>{positions.map(position=><option key={position.id} value={position.id}>{position.title}</option>)}</select></div><div className="flex items-center gap-2"><Filter size={14} className="shrink-0 text-[#7b8781]"/><select value={decisionFilter} onChange={event=>setDecisionFilter(event.target.value)} className="input"><option value="ALL">全部HR结论</option>{Object.entries(decisions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></div>
      {loading?<div className="p-5"><LoadingState label="正在读取候选人数据…"/></div>:error?<div className="m-5 flex flex-col items-center rounded-xl border border-[#efd5d1] bg-[#fff6f4] p-6 text-center"><AlertCircle size={22} className="text-[#b75a50]"/><p className="mt-3 text-sm font-semibold">候选人数据读取失败</p><p className="mt-1 text-xs text-[#8b615c]">{error}</p><button onClick={()=>void load()} className="btn-secondary mt-4"><RefreshCw size={14}/>重新读取</button></div>:filtered.length===0?<div className="p-5"><EmptyState title="暂无符合条件的候选人" description="添加候选人后，可在这里维护人才库和招聘流程"/></div>:<div className="divide-y divide-[#e9eeeb]">{filtered.map(item=><Link href={`/candidates/${item.id}`} key={item.id} className="grid items-center gap-4 px-5 py-4 hover:bg-[#fbfcfb] md:grid-cols-[1.05fr_1.3fr_90px_110px_auto]"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#eef4f1] text-brand-700"><UserRound size={17}/></div><div><p className="text-sm font-semibold">{item.displayName}</p><p className="mt-1 text-[11px] text-[#7e8a84]">{item.currentRole||"当前职位待补充"} · {item.yearsOfExperience??0}年</p></div></div><div>{item.applications.length?<div className="space-y-1">{item.applications.slice(0,2).map(application=><p key={application.id} className="text-xs"><span className="font-medium">{application.job.title}</span><span className="ml-2 text-[#7d8982]">{stageLabel(application.stage)}</span></p>)}</div>:<span className="badge">人才库 · 未关联职位</span>}<div className="mt-2 flex gap-1">{item.skills.slice(0,2).map(skill=><span key={skill} className="badge !px-2 !py-0.5">{skill}</span>)}</div></div><div><p className="text-xl font-bold text-brand-700">{item.latestMatch?.overallScore??"—"}{item.latestMatch&&<span className="text-xs">%</span>}</p><p className="text-[10px] text-[#89948e]">匹配度</p></div><span className="w-fit rounded-full bg-[#f1f4f2] px-2.5 py-1 text-[11px] font-semibold text-[#65726b]">{decisions[item.latestMatch?.hrDecision||"PENDING"]}</span><ChevronRight size={16} className="text-[#9aa49f]"/></Link>)}</div>}
    </div>
  </div>
}
