"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDown, BarChart3, Lightbulb, RefreshCw, Sparkles, TrendingUp } from "lucide-react";
import { AiNotice, EmptyState, LoadingState, PageHeader } from "@/components/ui";
import { FUNNEL_STAGES, getFunnelRates, percentage } from "@/lib/funnel-analysis";
import type { FunnelAnalysis, FunnelData } from "@/lib/types";

type Position={id:string;title:string;status:string};
type ResponseData={jobs:Position[];selectedJobId:string|null;funnel:FunnelData;analysis:FunnelAnalysis|null};
type DiagnosisResponse={result:FunnelAnalysis;meta:{provider:string;model:string}};
const emptyFunnel:FunnelData={received:0,screened:0,interviewed:0,offersMade:0,offersAccepted:0,onboarded:0};

export default function FunnelPage(){
  const [data,setData]=useState<ResponseData|null>(null);const [positionId,setPositionId]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [diagnosing,setDiagnosing]=useState(false);const [diagnosis,setDiagnosis]=useState<DiagnosisResponse|null>(null);
  async function load(selected=positionId){setLoading(true);setError("");setDiagnosis(null);try{const response=await fetch(`/api/funnel${selected?`?jobId=${encodeURIComponent(selected)}`:""}`);const result=await response.json();if(!response.ok)throw new Error(result.error||"招聘漏斗读取失败");setData(result)}catch(e){setError(e instanceof Error?e.message:"招聘漏斗读取失败")}finally{setLoading(false)}}
  useEffect(()=>{void load("")},[]);
  const funnel=data?.funnel??emptyFunnel;const rates=useMemo(()=>getFunnelRates(funnel),[funnel]);const analysis=diagnosis?.result??data?.analysis??null;const selectedTitle=positionId?data?.jobs.find(job=>job.id===positionId)?.title||"所选职位":"全部招聘职位";
  async function diagnose(){if(!funnel.received)return;setDiagnosing(true);setError("");try{const response=await fetch("/api/ai/funnel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(funnel)});const result=await response.json();if(!response.ok)throw new Error(result.error||"诊断失败");setDiagnosis(result)}catch(e){setError(e instanceof Error?e.message:"诊断失败")}finally{setDiagnosing(false)}}
  const severityClass=analysis?.severity==="高风险"?"bg-[#fde7e3] text-[#a4483f]":analysis?.severity==="需关注"?"bg-[#fff0cf] text-[#8a611f]":"bg-brand-100 text-brand-700";
  return <div className="fade-up"><PageHeader eyebrow="Recruiting Analytics" title="招聘漏斗" description="漏斗阶段完全来自候选人的实际招聘流程，修改候选人阶段后会自动同步。" action={<div className="flex gap-2"><button onClick={()=>void load()} className="btn-secondary"><RefreshCw size={15}/>刷新数据</button><button onClick={diagnose} disabled={diagnosing||!funnel.received} className="btn-primary"><Sparkles size={15}/>{diagnosing?"诊断中…":"生成 AI 诊断"}</button></div>}/>
    <div className="mb-5 panel flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold">统计范围</p><p className="mt-1 text-[11px] text-[#7d8982]">候选人可进入多个职位流程，因此全部职位按招聘流程人次统计。</p></div><select className="input !w-full sm:!w-72" value={positionId} onChange={event=>{const value=event.target.value;setPositionId(value);void load(value)}}><option value="">全部招聘职位</option>{data?.jobs.map(job=><option key={job.id} value={job.id}>{job.title}</option>)}</select></div>
    {error&&<div className="mb-4 rounded-xl bg-[#fff3f1] px-4 py-3 text-xs text-[#a84d43]">{error}</div>}{loading?<div className="panel p-5"><LoadingState label="正在读取实际招聘流程…"/></div>:!funnel.received?<EmptyState title="暂无招聘流程数据" description="在职位管理或候选人管理中添加候选人并关联职位后，漏斗会自动生成"/>:<>
      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{label:"初筛通过率",value:rates.screen,tip:"收到简历 → 通过初筛"},{label:"面试转化率",value:rates.interview,tip:"通过初筛 → 面试"},{label:"Offer 接受率",value:rates.accept,tip:"发出 Offer → 接受"},{label:"整体到岗率",value:rates.overall,tip:"收到简历 → 入职"}].map(item=><div key={item.label} className="panel p-5"><div className="flex items-center justify-between"><p className="text-xs text-[#6d7972]">{item.label}</p><div className={`grid size-8 place-items-center rounded-lg ${item.value<40?"bg-[#fff4e5] text-[#b77723]":"bg-brand-50 text-brand-600"}`}>{item.value<40?<AlertTriangle size={15}/>:<TrendingUp size={15}/>}</div></div><p className="mt-4 text-3xl font-bold">{item.value}%</p><p className="mt-1 text-[11px] text-[#89948e]">{item.tip}</p></div>)}</div>
      <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="panel p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">{selectedTitle} · 招聘漏斗</h2><p className="mt-1 text-xs text-[#7e8a84]">共 {funnel.received} 人次进入当前统计范围</p></div><span className="badge">实时数据</span></div><div className="space-y-3">{FUNNEL_STAGES.map((stage,index)=>{const width=Math.max(funnel[stage.key]?10:1,percentage(funnel[stage.key],funnel.received));const previous=index?funnel[FUNNEL_STAGES[index-1].key]:funnel.received;return <div key={stage.key}><div className="flex items-center justify-between text-xs"><span className="font-medium">{stage.label}</span><span className="font-bold">{funnel[stage.key]}</span></div><div className="mt-1.5 h-9 rounded-lg bg-[#eef2ef]"><div className="flex h-9 items-center rounded-lg bg-gradient-to-r from-[#83bda4] to-brand-500 px-3 text-[10px] font-semibold text-white" style={{width:`${width}%`}}>{index?`${percentage(funnel[stage.key],previous)}% 转化`:"100% 进入流程"}</div></div></div>})}</div></section>
        <section className="panel overflow-hidden">{analysis?<><div className="border-b border-[#e4ebe7] bg-[#f1f8f4] p-5"><div className="flex items-center gap-2"><div className="grid size-8 place-items-center rounded-lg bg-white text-brand-600"><Sparkles size={16}/></div><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">招聘漏斗诊断</h2><p className="truncate text-[11px] text-[#7b8881]">{diagnosis?`${diagnosis.meta.provider} · ${diagnosis.meta.model}`:"确定性规则诊断"}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${severityClass}`}>{analysis.severity}</span></div></div><div className="p-5"><p className="text-[11px] font-semibold uppercase tracking-wider text-[#8a958f]">最低转化环节</p><div className="mt-2 flex items-center gap-2 text-lg font-bold">{analysis.bottleneck.split("→")[0]}<ArrowDown size={16} className="text-[#b36852]"/>{analysis.bottleneck.split("→")[1]}</div><p className="mt-2 text-xs leading-5 text-[#6d7972]">{analysis.summary}</p><div className="my-5 h-px bg-[#e9eeeb]"/><p className="text-xs font-semibold">可能原因假设</p><ul className="mt-3 space-y-2">{analysis.possibleCauses.map((cause,index)=><li key={cause} className="flex gap-2 text-xs leading-5 text-[#65726b]"><span className="font-bold text-[#a87538]">{index+1}.</span>{cause}</li>)}</ul><div className="mt-5 rounded-xl bg-brand-50 p-4"><p className="flex items-center gap-2 text-xs font-semibold text-brand-700"><Lightbulb size={14}/>建议下一步</p><ul className="mt-2 space-y-2">{analysis.recommendations.map(item=><li key={item} className="text-xs leading-5 text-[#5d7066]">· {item}</li>)}</ul></div></div></>:<div className="p-5 text-xs text-[#6d7972]">暂无诊断结果。</div>}</section></div>
      <div className="mt-6 panel p-5"><div className="mb-5 flex items-center gap-2"><BarChart3 size={17} className="text-brand-600"/><h2 className="font-semibold">阶段人数明细</h2></div><div className="grid gap-3 md:grid-cols-6">{FUNNEL_STAGES.map(stage=><div key={stage.key} className="rounded-xl border border-[#e5eae7] p-4"><p className="text-[11px] text-[#7d8982]">{stage.label}</p><p className="mt-2 text-xl font-bold">{funnel[stage.key]}</p></div>)}</div></div><div className="mt-6"><AiNotice/></div>
    </>}
  </div>
}
