"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertCircle, Archive, BriefcaseBusiness, Calendar, MapPin, Plus, RefreshCw, Search, Users } from "lucide-react";
import { EmptyState, LoadingState, PageHeader } from "@/components/ui";

type Job = { id:string;title:string;department:string|null;location:string|null;status:string;createdAt:string;analyses:Array<{jobType:string|null}>;candidateCount:number;currentStage:string;progress:number };

export default function JobsPage(){
  const [jobs,setJobs]=useState<Job[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/jobs");const data=await response.json();if(!response.ok)throw new Error(data.error||"职位数据读取失败");setJobs(data.jobs||[])}catch(e){setError(e instanceof Error?e.message:"职位数据读取失败")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>jobs.filter(job=>job.title.toLowerCase().includes(query.toLowerCase())||job.department?.includes(query)),[jobs,query]);
  async function toggle(job:Job){await fetch(`/api/jobs/${job.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:job.status==="CLOSED"?"ACTIVE":"CLOSED"})});void load()}
  return <div className="fade-up"><PageHeader eyebrow="Job Workspace" title="职位管理" description="统一管理已确认的职位画像、招聘流程人数与招聘状态。" action={<Link href="/jd-analysis" className="btn-primary"><Plus size={15}/>新建职位分析</Link>}/>
    <div className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#e7ece9] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-sm"><Search size={15} className="absolute left-3 top-3 text-[#8a958f]"/><input value={query} onChange={e=>setQuery(e.target.value)} className="input !pl-9" placeholder="搜索职位或部门"/></div><div className="flex gap-2"><span className="badge">{jobs.filter(x=>x.status==="ACTIVE").length} 个进行中</span><span className="badge">{jobs.reduce((n,x)=>n+x.candidateCount,0)} 人次进入流程</span></div></div>
      {loading?<div className="p-5"><LoadingState label="正在读取职位数据…"/></div>:error?<div className="m-5 flex flex-col items-center rounded-xl border border-[#efd5d1] bg-[#fff6f4] p-6 text-center"><AlertCircle size={22} className="text-[#b75a50]"/><p className="mt-3 text-sm font-semibold">职位数据读取失败</p><p className="mt-1 text-xs text-[#8b615c]">{error}</p><button onClick={()=>void load()} className="btn-secondary mt-4"><RefreshCw size={14}/>重新读取</button></div>:filtered.length===0?<div className="p-5"><EmptyState title="暂无职位" description="完成一次JD分析并保存后，职位会出现在这里"/></div>:<div className="divide-y divide-[#e9eeeb]">{filtered.map(job=><div key={job.id} className="grid items-center gap-4 px-5 py-5 hover:bg-[#fbfcfb] md:grid-cols-[1.35fr_.7fr_.8fr_auto]"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-600"><BriefcaseBusiness size={18}/></div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{job.title}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${job.status==="ACTIVE"?"bg-brand-50 text-brand-700":"bg-[#f1f3f2] text-[#7c8781]"}`}>{job.status==="ACTIVE"?"招聘中":"已关闭"}</span></div><p className="mt-1 text-xs text-[#7e8a84]">{job.analyses[0]?.jobType||"待确认画像"}</p></div></div><div className="space-y-1 text-xs text-[#6d7972]"><p className="flex items-center gap-2"><MapPin size={13}/>{job.location||"地点待确认"}</p><p className="flex items-center gap-2"><Calendar size={13}/>{new Date(job.createdAt).toLocaleDateString("zh-CN")}</p></div><div><p className="flex items-center gap-2 text-sm font-semibold"><Users size={15} className="text-brand-600"/>{job.candidateCount}</p><p className="mt-1 text-[11px] text-[#89948e]">{job.currentStage} · 流程进度 {job.progress}%</p></div><div className="flex flex-wrap justify-end gap-2"><Link href={`/candidates/new?positionId=${job.id}`} className="btn-primary !px-3 !py-2"><Plus size={14}/>添加候选人</Link><button onClick={()=>toggle(job)} className="btn-secondary !px-3 !py-2"><Archive size={14}/>{job.status==="CLOSED"?"重新开启":"关闭职位"}</button></div></div>)}</div>}
    </div>
  </div>
}
